export interface BopomofoSymbol {
  id: string;
  symbol: string;
  group: 'consonant' | 'vowel' | 'compound';
  exampleWord: string;
  exampleEmoji: string;
  audioPath: string;
  imagePath: string;
  color: string;
}

const CONSONANT_COLORS = ['#FF6B6B', '#FF8E53', '#FFC851', '#4ECDC4'];
const VOWEL_COLORS = ['#45B7D1', '#96CEB4', '#DDA0DD', '#98D8C8'];

export const BOPOMOFO_SYMBOLS: BopomofoSymbol[] = [
  // Consonants (聲母) — 21 total
  {
    id: 'b',
    symbol: 'ㄅ',
    group: 'consonant',
    exampleWord: '杯子',
    exampleEmoji: '🥤',
    audioPath: '/audio/bopomofo/b.mp3',
    imagePath: '/images/bopomofo/b.svg',
    color: CONSONANT_COLORS[0],
  },
  {
    id: 'p',
    symbol: 'ㄆ',
    group: 'consonant',
    exampleWord: '蘋果',
    exampleEmoji: '🍎',
    audioPath: '/audio/bopomofo/p.mp3',
    imagePath: '/images/bopomofo/p.svg',
    color: CONSONANT_COLORS[1],
  },
  {
    id: 'm',
    symbol: 'ㄇ',
    group: 'consonant',
    exampleWord: '貓',
    exampleEmoji: '🐱',
    audioPath: '/audio/bopomofo/m.mp3',
    imagePath: '/images/bopomofo/m.svg',
    color: CONSONANT_COLORS[2],
  },
  {
    id: 'f',
    symbol: 'ㄈ',
    group: 'consonant',
    exampleWord: '飛機',
    exampleEmoji: '✈️',
    audioPath: '/audio/bopomofo/f.mp3',
    imagePath: '/images/bopomofo/f.svg',
    color: CONSONANT_COLORS[3],
  },
  {
    id: 'd',
    symbol: 'ㄉ',
    group: 'consonant',
    exampleWord: '蛋糕',
    exampleEmoji: '🎂',
    audioPath: '/audio/bopomofo/d.mp3',
    imagePath: '/images/bopomofo/d.svg',
    color: CONSONANT_COLORS[0],
  },
  {
    id: 't',
    symbol: 'ㄊ',
    group: 'consonant',
    exampleWord: '兔子',
    exampleEmoji: '🐰',
    audioPath: '/audio/bopomofo/t.mp3',
    imagePath: '/images/bopomofo/t.svg',
    color: CONSONANT_COLORS[1],
  },
  {
    id: 'n',
    symbol: 'ㄋ',
    group: 'consonant',
    exampleWord: '牛',
    exampleEmoji: '🐄',
    audioPath: '/audio/bopomofo/n.mp3',
    imagePath: '/images/bopomofo/n.svg',
    color: CONSONANT_COLORS[2],
  },
  {
    id: 'l',
    symbol: 'ㄌ',
    group: 'consonant',
    exampleWord: '老虎',
    exampleEmoji: '🐯',
    audioPath: '/audio/bopomofo/l.mp3',
    imagePath: '/images/bopomofo/l.svg',
    color: CONSONANT_COLORS[3],
  },
  {
    id: 'g',
    symbol: 'ㄍ',
    group: 'consonant',
    exampleWord: '狗',
    exampleEmoji: '🐶',
    audioPath: '/audio/bopomofo/g.mp3',
    imagePath: '/images/bopomofo/g.svg',
    color: CONSONANT_COLORS[0],
  },
  {
    id: 'k',
    symbol: 'ㄎ',
    group: 'consonant',
    exampleWord: '恐龍',
    exampleEmoji: '🦕',
    audioPath: '/audio/bopomofo/k.mp3',
    imagePath: '/images/bopomofo/k.svg',
    color: CONSONANT_COLORS[1],
  },
  {
    id: 'h',
    symbol: 'ㄏ',
    group: 'consonant',
    exampleWord: '蝴蝶',
    exampleEmoji: '🦋',
    audioPath: '/audio/bopomofo/h.mp3',
    imagePath: '/images/bopomofo/h.svg',
    color: CONSONANT_COLORS[2],
  },
  {
    id: 'j',
    symbol: 'ㄐ',
    group: 'consonant',
    exampleWord: '雞',
    exampleEmoji: '🐔',
    audioPath: '/audio/bopomofo/j.mp3',
    imagePath: '/images/bopomofo/j.svg',
    color: CONSONANT_COLORS[3],
  },
  {
    id: 'q',
    symbol: 'ㄑ',
    group: 'consonant',
    exampleWord: '球',
    exampleEmoji: '⚽',
    audioPath: '/audio/bopomofo/q.mp3',
    imagePath: '/images/bopomofo/q.svg',
    color: CONSONANT_COLORS[0],
  },
  {
    id: 'x',
    symbol: 'ㄒ',
    group: 'consonant',
    exampleWord: '西瓜',
    exampleEmoji: '🍉',
    audioPath: '/audio/bopomofo/x.mp3',
    imagePath: '/images/bopomofo/x.svg',
    color: CONSONANT_COLORS[1],
  },
  {
    id: 'zh',
    symbol: 'ㄓ',
    group: 'consonant',
    exampleWord: '蜘蛛',
    exampleEmoji: '🕷️',
    audioPath: '/audio/bopomofo/zh.mp3',
    imagePath: '/images/bopomofo/zh.svg',
    color: CONSONANT_COLORS[2],
  },
  {
    id: 'ch',
    symbol: 'ㄔ',
    group: 'consonant',
    exampleWord: '車',
    exampleEmoji: '🚗',
    audioPath: '/audio/bopomofo/ch.mp3',
    imagePath: '/images/bopomofo/ch.svg',
    color: CONSONANT_COLORS[3],
  },
  {
    id: 'sh',
    symbol: 'ㄕ',
    group: 'consonant',
    exampleWord: '獅子',
    exampleEmoji: '🦁',
    audioPath: '/audio/bopomofo/sh.mp3',
    imagePath: '/images/bopomofo/sh.svg',
    color: CONSONANT_COLORS[0],
  },
  {
    id: 'r',
    symbol: 'ㄖ',
    group: 'consonant',
    exampleWord: '肉',
    exampleEmoji: '🥩',
    audioPath: '/audio/bopomofo/r.mp3',
    imagePath: '/images/bopomofo/r.svg',
    color: CONSONANT_COLORS[1],
  },
  {
    id: 'z',
    symbol: 'ㄗ',
    group: 'consonant',
    exampleWord: '字',
    exampleEmoji: '📝',
    audioPath: '/audio/bopomofo/z.mp3',
    imagePath: '/images/bopomofo/z.svg',
    color: CONSONANT_COLORS[2],
  },
  {
    id: 'c',
    symbol: 'ㄘ',
    group: 'consonant',
    exampleWord: '草莓',
    exampleEmoji: '🍓',
    audioPath: '/audio/bopomofo/c.mp3',
    imagePath: '/images/bopomofo/c.svg',
    color: CONSONANT_COLORS[3],
  },
  {
    id: 's',
    symbol: 'ㄙ',
    group: 'consonant',
    exampleWord: '蛇',
    exampleEmoji: '🐍',
    audioPath: '/audio/bopomofo/s.mp3',
    imagePath: '/images/bopomofo/s.svg',
    color: CONSONANT_COLORS[0],
  },

  // Vowels (韻母) — 16 total
  {
    id: 'a',
    symbol: 'ㄚ',
    group: 'vowel',
    exampleWord: '阿嬤',
    exampleEmoji: '👵',
    audioPath: '/audio/bopomofo/a.mp3',
    imagePath: '/images/bopomofo/a.svg',
    color: VOWEL_COLORS[0],
  },
  {
    id: 'o',
    symbol: 'ㄛ',
    group: 'vowel',
    exampleWord: '鵝',
    exampleEmoji: '🦢',
    audioPath: '/audio/bopomofo/o.mp3',
    imagePath: '/images/bopomofo/o.svg',
    color: VOWEL_COLORS[1],
  },
  {
    id: 'e',
    symbol: 'ㄜ',
    group: 'vowel',
    exampleWord: '餓',
    exampleEmoji: '😋',
    audioPath: '/audio/bopomofo/e.mp3',
    imagePath: '/images/bopomofo/e.svg',
    color: VOWEL_COLORS[2],
  },
  {
    id: 'eh',
    symbol: 'ㄝ',
    group: 'vowel',
    exampleWord: '耶',
    exampleEmoji: '🎉',
    audioPath: '/audio/bopomofo/eh.mp3',
    imagePath: '/images/bopomofo/eh.svg',
    color: VOWEL_COLORS[3],
  },
  {
    id: 'ai',
    symbol: 'ㄞ',
    group: 'vowel',
    exampleWord: '愛',
    exampleEmoji: '❤️',
    audioPath: '/audio/bopomofo/ai.mp3',
    imagePath: '/images/bopomofo/ai.svg',
    color: VOWEL_COLORS[0],
  },
  {
    id: 'ei',
    symbol: 'ㄟ',
    group: 'vowel',
    exampleWord: '杯',
    exampleEmoji: '🫙',
    audioPath: '/audio/bopomofo/ei.mp3',
    imagePath: '/images/bopomofo/ei.svg',
    color: VOWEL_COLORS[1],
  },
  {
    id: 'ao',
    symbol: 'ㄠ',
    group: 'vowel',
    exampleWord: '貓',
    exampleEmoji: '🐱',
    audioPath: '/audio/bopomofo/ao.mp3',
    imagePath: '/images/bopomofo/ao.svg',
    color: VOWEL_COLORS[2],
  },
  {
    id: 'ou',
    symbol: 'ㄡ',
    group: 'vowel',
    exampleWord: '狗',
    exampleEmoji: '🐶',
    audioPath: '/audio/bopomofo/ou.mp3',
    imagePath: '/images/bopomofo/ou.svg',
    color: VOWEL_COLORS[3],
  },
  {
    id: 'an',
    symbol: 'ㄢ',
    group: 'vowel',
    exampleWord: '安全',
    exampleEmoji: '🦺',
    audioPath: '/audio/bopomofo/an.mp3',
    imagePath: '/images/bopomofo/an.svg',
    color: VOWEL_COLORS[0],
  },
  {
    id: 'en',
    symbol: 'ㄣ',
    group: 'vowel',
    exampleWord: '恩',
    exampleEmoji: '🙏',
    audioPath: '/audio/bopomofo/en.mp3',
    imagePath: '/images/bopomofo/en.svg',
    color: VOWEL_COLORS[1],
  },
  {
    id: 'ang',
    symbol: 'ㄤ',
    group: 'vowel',
    exampleWord: '螃蟹',
    exampleEmoji: '🦀',
    audioPath: '/audio/bopomofo/ang.mp3',
    imagePath: '/images/bopomofo/ang.svg',
    color: VOWEL_COLORS[2],
  },
  {
    id: 'eng',
    symbol: 'ㄥ',
    group: 'vowel',
    exampleWord: '鷹',
    exampleEmoji: '🦅',
    audioPath: '/audio/bopomofo/eng.mp3',
    imagePath: '/images/bopomofo/eng.svg',
    color: VOWEL_COLORS[3],
  },
  {
    id: 'er',
    symbol: 'ㄦ',
    group: 'vowel',
    exampleWord: '耳朵',
    exampleEmoji: '👂',
    audioPath: '/audio/bopomofo/er.mp3',
    imagePath: '/images/bopomofo/er.svg',
    color: VOWEL_COLORS[0],
  },
  {
    id: 'yi',
    symbol: 'ㄧ',
    group: 'vowel',
    exampleWord: '一',
    exampleEmoji: '☝️',
    audioPath: '/audio/bopomofo/yi.mp3',
    imagePath: '/images/bopomofo/yi.svg',
    color: VOWEL_COLORS[1],
  },
  {
    id: 'wu',
    symbol: 'ㄨ',
    group: 'vowel',
    exampleWord: '烏龜',
    exampleEmoji: '🐢',
    audioPath: '/audio/bopomofo/wu.mp3',
    imagePath: '/images/bopomofo/wu.svg',
    color: VOWEL_COLORS[2],
  },
  {
    id: 'yu',
    symbol: 'ㄩ',
    group: 'vowel',
    exampleWord: '魚',
    exampleEmoji: '🐟',
    audioPath: '/audio/bopomofo/yu.mp3',
    imagePath: '/images/bopomofo/yu.svg',
    color: VOWEL_COLORS[3],
  },
];

export function getSymbolById(id: string): BopomofoSymbol | undefined {
  return BOPOMOFO_SYMBOLS.find((s) => s.id === id);
}
